name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2.3.5
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, build, and test
        run: |
          yarn install --immutable
          yarn run build
          yarn run lint --since origin/master --parallel
          yarn run test --since origin/master
        env:
          DB_URL_TJ: ${{ secrets.DB_URL_TJ }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
          HANDBALL_PLANET_URL: ${{ secrets.HANDBALL_PLANET_URL }}
          HANDBALL_NO: ${{ secrets.HANDBALL_NO }}
