name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'trainingjournal_test'
          mysql user: 'root'
          mysql password: ${{ secrets.tjRootPassword }}
      - name: yarn install, build, and test
        run: |
          yarn install --frozen-lockfile
          yarn run test
          yarn run typecheck
          yarn run lint
          yarn workspace @tbergq/graphql test-bc
          yarn relay --validate
        env:
          DB_URL_TJ: ${{ secrets.DB_URL_TJ }}
