name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, build, and test
        run: |
          yarn install --frozen-lockfile
          yarn run build
          yarn run typecheck
          yarn run lint --since origin/master
          yarn run test --since origin/master
          yarn relay --validate
        env:
          DB_URL_TJ: ${{ secrets.DB_URL_TJ }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
