name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: yarn install --immutable
      - run: yarn nx affected --target=build --parallel --max-parallel=3 --base=origin/master
      - run: yarn nx affected --target=test --parallel --max-parallel=2 --base=origin/master
      - run: yarn nx affected --target=lint --parallel --max-parallel=2 --base=origin/master
        env:
          DB_URL_TJ: ${{ secrets.DB_URL_TJ }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
          HANDBALL_PLANET_URL: ${{ secrets.HANDBALL_PLANET_URL }}
          HANDBALL_NO: ${{ secrets.HANDBALL_NO }}
          NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: yarn install --immutable
      - run: yarn nx affected --target=build --parallel --max-parallel=3 --base=origin/master
      - run: yarn nx affected --target=test --parallel --max-parallel=2 --base=origin/master
      - run: yarn nx affected --target=lint --parallel --max-parallel=2 --base=origin/master
        env:
          DB_URL_TJ: ${{ secrets.DB_URL_TJ }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
          HANDBALL_PLANET_URL: ${{ secrets.HANDBALL_PLANET_URL }}
          HANDBALL_NO: ${{ secrets.HANDBALL_NO }}
          NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
