name: Deploy graphql

# on: [push]
on:
  push:
    branches: [master]
    paths:
      - 'apps/graphql/**'
      - 'packages/graphql-persistence/**'
      - 'packages/graphql-services/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js 14
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.x
      - name: deploy graphql
        run: |
          yarn install --frozen-lockfile
          yarn run build
          yarn workspace @tbergq/graphql es-build
          cd apps/graphql
          yarn vercel --prod --confirm --token=${ZEIT_TOKEN}
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
          GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
