name: Deploy tvhelper

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: deploy tvhelper
        run: |
          docker login -u tbergq -p "${{ secrets.DOCKER_HUB_TOKEN }}"
          yarn install --frozen-lockfile
          yarn global add heroku
          yarn run build
          yarn workspace @tbergq/tvhelper docker:build
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
