name: Deploy grahpql

on:
  push:
    branches: [master]
    paths:
      - 'apps/graphql/**'
      - 'packages/graphql-persistence/**'
      - 'packages/graphql-services/**'
      - 'packages/tvhelper-persistence/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
      - name: deploy graphql
        run: |
          yarn install --frozen-lockfile
          yarn run build
          yarn workspace @tbergq/graphql deploy
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
          GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
