name: Deploy trainingjournal

on:
 push:
   branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: deploy trainingjournal
        run: |
          docker login -u tbergq -p "${{ secrets.DOCKER_HUB_TOKEN }}"
          yarn install --frozen-lockfile
          yarn global add heroku
          yarn workspace @tbergq/trainingjournal deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          GRAPHQL_URL: https://tbergq-tj.herokuapp.com/api/graphql
