name: Deploy tvhelper

# on: [push]
on:
  push:
    branches: [master]
    paths:
      - 'apps/tvhelper/**'
      - 'packages/components/**'
      - 'packages/theme/**'
      - 'packages/formik-wrapper/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2
      - name: Use Node.js 16
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.x
      - name: deploy tvhelper
        run: |
          docker login -u tbergq -p "${{ secrets.DOCKER_HUB_TOKEN }}"
          yarn dlx heroku container:login
          docker build . -t tvhelper:latest -f apps/tvhelper/Dockerfile
          docker tag tvhelper:latest registry.heroku.com/tbergq-tvhelper/web
          docker push registry.heroku.com/tbergq-tvhelper/web
          yarn dlx heroku container:release web -a tbergq-tvhelper
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
