name: Deploy tvhelper

# on: [push]
on:
  push:
    branches: [master]
    paths:
      - 'apps/tvhelper/**'
      - 'packages/components/**'
      - 'packages/theme/**'
      - 'packages/formik-wrapper/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: deploy tvhelper
        run: flyctl deploy --config apps/tvhelper/fly.toml --build-target runner --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
